services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-store
          property: connectionString

  - type: redis
    name: redis-store

  - type: web
    name: vue-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    staticPublishPath: frontend/dist
